# -*- coding: utf-8 -*-
"""Hora+da+pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYcAfTjCIqUrqDpaGzV_L-MYetZqD7lv

# Sobre o notebook

A "hora da prática" é uma atividade do curso de Python para Data Science da Alura que contém diversos desafios envolvendo os aprendizados de cada aula.

O notebook "hora da pratica" é um notebook construído com espaço para as células dos desafios propostos no curso, com ele você tem espaço para construir e executar suas soluções

## Aula 1 - Introdução ao Python

### Questão 1

Imprima a frase `Escola de Dados da Alura!`
"""

print('Escola de Dados da Alura!')

"""### Questão 2
Imprima na tela seu nome e seu sobrenome seguindo a estrutura abaixo:
```
Nome: [seu nome]
Sobrenome: [seu sobrenome]
```

"""

nome = 'jose'
sobrenome = 'francisco'

print(f'Nome: {nome}\nSobrenome: {sobrenome}')

"""### Questão 3
Imprima o seu primeiro nome letra a letra. Por exemplo, nome é Mirla, então eu obtenho a seguinte saída:
```
M
I
R
L
A
```

"""

print(f'j\no\ns\ne')

"""### Questão 4
Imprima o dia do seu nascimento em formato `dia mês ano`. Os valores de dia e ano não podem estar entre aspas. O formato deve estar como no exemplo, supondo uma data de aniversário dia 28 de fevereiro de 2003:
```
28 fevereiro 2003
```
"""

dia = 11
mes = 'março'
ano = 2007

print(dia, mes, ano)

"""
### Questão 5
Imprima em um único print o atual ano que você está fazendo esse curso, o valor do ano deve ser um dado numérico. A saída do print deve ser a seguinte:
```
Ano atual: [ano]
```
"""

ano = 2026
print('Ano atual:', ano)

"""## Aula 2 - Manipulando dados no Python

### Coleta e amostragem de dados

#### Questão 1
Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
"""

nome = input('Digite seu nome:\n')
print('Olá', nome)

"""#### Questão 2
Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.
"""

nome = input('Digite seu nome:\n')
idade = int(input('Digite sua idade:\n'))
print('Olá, {}, você tem {}'.format(nome, idade))

"""#### Questão 3
Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.
"""

nome = input('Digite seu nome:\n')
idade = int(input('Digite sua idade:\n'))
altura = float(input('Digite sua altura:\n'))
print('Olá, {}, você tem {} anos e mede {} metros'.format(nome, idade, altura))

"""### Calculadora com operadores

#### Questão 1

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número:\n'))

print('Soma:', n1 + n2)

"""#### Questão 2
Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número:\n'))
n3 = float(input('Digite o terceiro número:\n'))

print('Soma:', n1 + n2 + n3)

"""#### Questão 3
Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número:\n'))

print('Subtração:', n1 - n2)

"""#### Questão 4

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número:\n'))

print('Multiplicação:', n1 * n2)

"""#### Questão 5

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.

"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número (DIFERENTE DE 0!!!):\n'))

print('Divisão:', n1 / n2)

"""#### Questão 6

Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número:\n'))

print('Exponenciação:', n1 ** n2)

"""#### Questão 7
Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número (DIFERENTE DE 0!!!):\n'))

print('Divisão inteira:', n1 // n2)

"""#### Questão 8

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

print("======= Calculadora =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número (DIFERENTE DE 0!!!):\n'))

print('Resto da divisão:', n1 % n2)

"""#### Questão 9

Crie um código que solicita 3 notas de um estudante e imprima a média das notas.
"""

print("======= Média das 3 notas de um estudante =======")
n1 = float(input('Digite o primeiro número:\n'))
n2 = float(input('Digite o segundo número:\n'))
n3 = float(input('Digite o terceiro número:\n'))

print('Média do estudante', (n1 + n2 + n3)/3)

"""#### Questão 10

Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.
"""

print("======= Calculadora da média ponderada =======")
n1 = 5 * 1
n2 = 12 * 2
n3 = 20 * 3
n4 = 15 * 4

print('Média ponderada:', (n1 + n2 + n3 + n4) / (1+2+3+4))

"""### Editando textos

#### Questão 1

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
"""

frase = 'Olá gays do mundo '
print(frase)

"""#### Questão 2
Crie um código que solicite uma frase e depois imprima a frase na tela.
"""

frase1 = input('Digite sua frase:\n')
print(frase1)

"""#### Questão 3

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
"""

frase2 = input('Digite sua frase:\n')
print(frase2.upper())

"""#### Questão 4

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
"""

frase3 = input('Digite sua frase:\n')
print(frase3.lower())

"""#### Questão 5

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
"""

frase4 = ' macacos comem banana '
print(frase4.strip())

"""#### Questão 6

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
"""

frase5 = input('Digite sua frase:\n')
print(frase5.strip())

"""#### Questão 7


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
"""

frase6 = input('Digite sua frase:\n')
print(frase6.strip().lower())

"""#### Questão 8

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`e`” trocadas pela letra “`f`”.
"""

frase7 = input('Digite sua frase:\n')
print(frase7.lower().replace('e', 'f'))

"""#### Questão 9


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`a`” trocadas pela caractere  “`@`”.
"""

frase8 = input('Digite sua frase:\n')
print(frase8.lower().replace('a', '@'))

"""#### Questão 10


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “`s`” trocadas pelo caractere  “`$`”.
"""

frase8 = input('Digite sua frase:\n')
print(frase8.lower().replace('s', '$'))

"""## Aula 3 - Estruturas condicionais

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior.
"""

n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))

if n1 > n2:
  print(n1, 'é o maior número')
else:
  print(n2, 'é o maior número')

"""#### Questão 2
Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).
"""

percentual_de_crescimento = float(input('Digite o percentual de crescimento da empresa: '))
if percentual_de_crescimento > 0:
  print('Houve um crescimento!')
elif percentual_de_crescimento < 0:
  print('Houve um decrescimento.')
else:
  print('Não houve variação.')

"""#### Questão 3
Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante.
"""

letra = input('Digite uma letra: ')
vogal = 'a', 'e', 'i', 'o', 'u'
if letra in vogal:
  print('A letra é uma vogal')
else:
  print('A letra é uma consoante')

"""#### Questão 4
Escreva um programa que leia valores médios de preços de um modelo de carro por 3 anos consecutivos e exiba o valor mais alto e mais baixo entre esses três anos.
"""

ano1 = float(input('Digite o valor do modelo do carro no 1° ano: '))
ano2 = float(input('Digite o valor do modelo do carro no 2° ano: '))
ano3 = float(input('Digite o valor do modelo do carro no 3° ano: '))

if ano1 > ano2 and ano1 > ano3:
  print(f'O valor mais alto do modelo do carro foi de {ano1}')
elif ano2 > ano1 and ano2 > ano3:
  print(f'O valor mais alto do modelo do carro foi de {ano2}')
else:
  print(f'O valor mais alto do modelo do carro foi de {ano3}')
if ano1 < ano2 and ano1 < ano3:
  print(f'O valor mais baixo do modelo do carro foi de {ano1}')
elif ano2 < ano1 and ano2 < ano3:
  print(f'O valor mais baixo do modelo do carro foi de {ano2}')
else:
  print(f'O valor mais baixo do modelo do carro foi de {ano3}')

"""#### Questão 5
Escreva um programa que pergunte sobre o preço de três produtos e indique qual é o produto mais barato para comprar.
"""

p1 = float(input('Digite o valor do produto 1: '))
p2 = float(input('Digite o valor do produto 2: '))
p3 = float(input('Digite o valor do produto 3: '))

menor = p1
if p2 < p1:
  menor = p2
if p3 < p2:
  menor = p3

print(f'O produto mais barato é o de valor {menor}')

"""#### Questão 6
Escreva um programa que leia três números e os exiba em ordem decrescente.
"""

n1 = float(input('Digite o valor do número 1: '))
n2 = float(input('Digite o valor do número 2: '))
n3 = float(input('Digite o valor do número 3: '))

if n1 > n2 and n1 > n3:
  print(n1)
  if n2 > n3:
    print(n2)
    print(n3)
if n2 > n1 and n2 > n3:
  print(n2)
  if n1 > n3:
    print(n1)
    print(n3)
  else:
    print(n3)
    print(n1)
if n3 > n2 and n3 > n1:
  print(n3)
  if n2 > n1:
    print(n2)
    print(n1)
  else:
    print(n1)
    print(n2)

"""#### Questão 7
Escreva um programa que pergunte em qual turno a pessoa usuária estuda ("manhã", "tarde" ou "noite") e exiba a mensagem "Bom Dia!", "Boa Tarde!", "Boa Noite!", ou "Valor Inválido!", conforme o caso.
"""

turno = input('Em qual turno você estuda? (manhã - tarde - noite) \n')

if turno == 'manhã':
  print('Bom Dia!')
elif turno == 'tarde':
  print('Boa Tarde!')
else:
  print('Boa Noite!')

"""#### Questão 8
Escreva um programa que peça um número inteiro à pessoa usuária e determine se ele é par ou ímpar. Dica: Você pode utilizar o operador módulo `%`.
"""

num = int(input('DIgite um número inteiro: '))

if num % 2 == 0:
  print(f'O número {num} é par')
else:
  print(f'O número {num} é impar')

"""#### Questão 9
Escreva um programa que peça um número à pessoa usuária e informe se ele é inteiro ou decimal.
"""

num = float(input('Digite um número: '))

if num % 1 == 0:
  print(f'O número {num} é inteiro')
else: print(f'O número {num} é decimal')

"""### Momento dos projetos

#### Questão 10
Um programa deve ser escrito para ler dois números e, em seguida, perguntar à pessoa usuária qual operação ele deseja realizar. O resultado da operação deve incluir informações sobre o número - se é par ou ímpar, positivo ou negativo e inteiro ou decimal.
"""

from ast import operator
n1 = float(input('Digite o valor do número 1: '))
operacao = input('Digite a operação que deseja realizar deseja realizar:\n-Soma (+)\n-Subtração (-)\n-Multiplicação (*)\n-Divisão (/)\n-Potência (**)\n')
n2 = float(input('Digite o valor do número 2: '))

resultado = ''

if operacao == '+':
  resultado = n1 + n2
elif operacao == '-':
  resultado = n1 - n2
elif operacao == '*':
  resultado = n1 * n2
elif operacao == '/':
  resultado = n1 / n2
elif operacao == '**':
  resultado = n1 ** n2
else: print('Operação inválida')

print(resultado)

if resultado % 2 == 0:
  print(f'O número {resultado} é par')
else:
  print(f'O número {resultado} é impar')

if resultado > 0:
  print(f'O número {resultado} é positivo')
elif resultado < 0:
  print(f'O número {resultado} é negativo')
else: print(f'O número é nulo')


if resultado % 1 == 0:
  print(f'O número {resultado} é inteiro')
else: print(f'O número {resultado} é decimal')

"""#### Questão 11
Escreva um programa que peça à pessoa usuária três números que representam os lados de um triângulo. O programa deve informar se os valores podem ser utilizados para formar um triângulo e, caso afirmativo, se ele é equilátero, isósceles ou escaleno. Tenha em mente algumas dicas:
- Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
- Triângulo Equilátero: três lados iguais;
- Triângulo Isósceles: quaisquer dois lados iguais;
- Triângulo Escaleno: três lados diferentes;

"""

print('Coletaremos os lados de um triângulo.')
lado1 = float(input('Digite o comprimento do primeiro lado: '))
lado2 = float(input('Digite o comprimento do segundo lado: '))
lado3 = float(input('Digite o comprimento do terceiro lado: '))


if (lado1 + lado2 > lado3) and (lado2 + lado3 > lado1) and (lado1 + lado3 > lado2):
    print('Os valores podem formar um triângulo!')

    if (lado1 == lado2) and (lado2 == lado3):
        print('O triângulo é equilátero.')
    elif (lado1 != lado2) and (lado2 != lado3) and (lado1 != lado3):
        print('O triângulo é escaleno.')
    else:
        print('O triângulo é isósceles.')
else:
    print('Os valores não podem formar um triângulo!')

"""#### Questão 12
Um estabelecimento está vendendo combustíveis com descontos variados. Para o etanol, se a quantidade comprada for até 15 litros, o desconto será de 2% por litro. Caso contrário, será de 4% por litro. Para o diesel, se a quantidade comprada for até 15 litros, o desconto será de 3% por litro. Caso contrário, será de 5% por litro. O preço do litro de diesel é R\$ 2,00 e o preço do litro de etanol é R\$ 1,70. Escreva um programa que leia a quantidade de litros vendidos e o tipo de combustível (E para etanol e D para diesel) e calcule o valor a ser pago pelo cliente. Tenha em mente algumas dicas:

- O do valor do desconto será a multiplicação entre preço do litro, quantidade de litros e o valor do desconto.
- O valor a ser pago por um cliente será o resultado da multiplicação do preço do litro pela quantidade de litros menos o valor de desconto resultante do cálculo.

"""

# Definindo as variáveis
tipo = input('Escolha o tipo de combustível: \n(D - Diesel | E - Etanol)')
# Quando for etanol
if tipo == 'E':
  quantidade = float(input('Quantidade: '))
  preco = 1.70

  if quantidade <= 15:
    valor_desconto = preco * quantidade * 0.02
    valor_pago = preco * quantidade - valor_desconto
    print(valor_pago)
  else:
    valor_desconto = preco * quantidade * 0.04
    valor_pago = preco * quantidade - valor_desconto
    print(valor_pago)
# Quando for Diesel
else:
  quantidade = float(input('Quantidade: '))
  preco = 2.00

  if quantidade <= 15:
    valor_desconto = preco * quantidade * 0.03
    valor_pago = preco * quantidade - valor_desconto
    print(valor_pago)
  else:
    valor_desconto = preco * quantidade * 0.05
    valor_pago = preco * quantidade - valor_desconto
    print(valor_pago)

"""#### Questão 13
Em uma empresa de venda de imóveis você precisa criar um código que analise os dados de vendas anuais para ajudar a diretoria na tomada de decisão. O código precisa coletar os dados de quantidade de venda durante os anos de 2022 e 2023 e fazer um cálculo de variação percentual. A partir do valor da variação, deve ser enviada às seguintes sugestões:
- Para variação acima de 20%: bonificação para o time de vendas.
- Para variação entre 2% e 20%: pequena bonificação para time de vendas.
- Para variação entre 2% e -10%: planejamento de políticas de incentivo às vendas.
- Para bonificações abaixo de -10%: corte de gastos.

"""

ano_2022 = float(input('Digite a quantidade de vendas do ano de 2022: '))
ano_2023 = float(input('Digite a quantidade de vendas do ano de 2023: '))

variacao = ano_2023 - ano_2022
variacaoPorcentagem = variacao / 100

print(f'Ocorreu uma variação de {variacaoPorcentagem}% ')
if variacaoPorcentagem > 20:
  print('Bonificação para o time de vendas')
elif variacaoPorcentagem > 2 and variacaoPorcentagem <= 20:
  print('Pequena bonificação para o time de vendas')
elif variacaoPorcentagem > -10 and variacaoPorcentagem <= 2:
  print('Planejamento de políticas de incentivo ás vendas')
else:
  print('Corte de gastos')

"""## Aula 4 - Estruturas de repetição

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça dois números inteiros e imprima todos os números inteiros entre eles.
"""

n1 = int(input("Digite um número inteiro: "))
n2 = int(input("Digite outro número inteiro: "))

if n1 < n2:
  for i in range(n1 + 1, n2):
    print(i)
elif n1 > n2:
  for i in range(n2 + 1, n1):
    print(i)
else: print('Os números são iguais')

"""#### Questão 2
Escreva um programa para calcular quantos dias levará para a colônia de uma bactéria A ultrapassar ou igualar a colônia de uma bactéria B, com base nas taxas de crescimento de 3% e 1,5% respectivamente. Considere que a colônia A inicia com 4 elementos e a colônia B com 10 elementos.
"""

#Definindo as colonias
colonia_A = 4
colonia_B = 10

#contagem de dias
dia = 0

#Repita até a colonia A ser maior
while colonia_A <= colonia_B:
    colonia_A *= 1 + 0.03
    colonia_B *= 1 + 0.015
    dia += 1

#Printando o resultado
print(f'Irá demorar {dia} dias pra a colônia da bactéria A superara a colônia da bactéria B')

"""#### Questão 3
Para tratar uma quantidade de 15 dados de avaliações de pessoas usuárias de um serviço da empresa, precisamos verificar se as notas são válidas. Então, escreva um programa que vai receber a nota de 0 a 5 de todos os dados e verificar se é um valor válido. Caso seja inserido uma nota acima de 5 ou abaixo de 0, repita até que a pessoa usuária insira um valor válido.
"""

#Iniciando a estrutura de repetição entre 1 e 16
for dados in range(1,16):
    #Definindo a nota de cada dado
    nota = int(input(f'Digite a nota do {dados}° dado para avaliar (0 a 5): '))

    #Analisando se a nota está entre 0 e 5
    while nota < 0 or nota > 5:
        print("Insira um valor entre 0 e 5")
        nota = int(input(f'Digite a nota do {dados}° dado para avaliar (0 a 5): '))

"""#### Questão 4
Desenvolva um programa que leia um conjunto indeterminado de temperaturas em Celsius e faça uma análise. Portanto, escreva um programa que leia temperaturas e informe a média delas. A leitura deve ser encerrada ao ser enviado o valor -273°C.
"""

#Iniciando o programa
temperatura = 0 # Somador da temperatura
ler_temperatura = float(input('Digite uma temperatura em graus Celsius: ')) # Coletamos a temperatura
contador = 0 # Quantas vezes o while rodou

while ler_temperatura != -273:
  temperatura += ler_temperatura # Somador da temperatura contando
  contador += 1 # Contador contando

  ler_temperatura = float(input('Digite uma temperatura em graus Celsius: ')) # Lendo as temperaturas

print(f'A média das temperaturas é {temperatura / contador}') # Escrever a média

"""#### Questão 5
Escreva um programa que calcule o fatorial de um número inteiro fornecido pela pessoa usuária. O fatorial de um número inteiro é a multiplicação desse número por todos os seus antecessores até o número 1. Por exemplo, o fatorial de 5 é 5 x 4 x 3 x 2 x 1 = 120.
"""

num = int(input('Informe um número inteiro: '))

fatorial = 1

i = num
while i > 0:
    fatorial *= i
    i -= 1

print(f'Fatorial de {num} é {fatorial}')

"""### Momento dos projetos

#### Questão 6
Escreva um programa que gere a tabuada de um número inteiro de 1 a 10, de acordo com a escolha da pessoa usuária. Como exemplo, para o número 2, a tabuada deve ser mostrada no seguinte formato:
```
Tabuada do 2:
2 x 1 = 2
2 x 2 = 4
[...]
2 x 10 = 20
```
"""

num = int(input('Digite um número inteiro para ver sua tabuada: '))

for i in range(1, 11):
  resultado = num * i
  print(f'{num} X {i} = {resultado}')

"""#### Questão 7
Os números primos possuem várias aplicações dentro da Ciência de Dados, por exemplo, na criptografia e segurança. Um número primo é aquele que é divisível apenas por um e por ele mesmo. Faça um programa que peça um número inteiro e determine se ele é ou não um número primo.
"""

num = int(input('Digite um número inteiro para ver se é primo ou não: '))

primo = True

if num <= 1:
   primo = False
else:
  for i in range(2, num):
    if num % i == 0:
      primo = False
      break

if primo:
  print(f'O número {num} é primo')
else: print(f'O número {num} não é primo')

"""#### Questão 8
Vamos entender a distribuição de idades de pensionistas de uma empresa de previdência. Escreva um programa que leia as idades de uma quantidade não informada de clientes e mostre a distribuição em intervalos de [0-25], [26-50], [51-75] e [76-100]. Encerre a entrada de dados com um número negativo.
"""

comeco = True

contador_0_25 = 0
contador_26_50 = 0
contador_51_75 = 0
contador_76_100 = 0

while comeco:
  idade = int(input('Digite uma idade: '))
  if idade < 0:
    comeco = False
  elif idade >= 0 and idade <= 25:
    contador_0_25 += 1
  elif idade >= 26 and idade <= 50:
    contador_26_50 += 1
  elif idade >= 51 and idade <= 75:
    contador_51_75 += 1
  elif idade >= 76 and idade <= 100:
    contador_76_100 += 1
  else: print('Idade inválida')

print('Idade de 0 até 25: ', contador_0_25)
print('Idade de 26 até 50: ', contador_26_50)
print('Idade de 51 até 75: ', contador_51_75)
print('Idade de 76 até 100: ', contador_76_100)

"""#### Questão 9
Em uma eleição para gerência em uma empresa com 20 funcionários, existem quatro candidatos. Escreva um programa que calcule o vencedor da eleição. A votação ocorreu da seguinte maneira:
- Cada funcionário votou em um dos quatro candidatos (representados pelos números 1, 2, 3 e 4).
- Também foram contabilizados os votos nulos (representado pelo número 5) e os votos em branco (representado pelo número 6).

Ao final da votação, o programa deve exibir o total de votos para cada candidato, o número de votos nulos e o número de votos em branco. Além disso, deve calcular e exibir a porcentagem de votos nulos em relação ao total de votos e a porcentagem de votos em branco em relação ao total de votos.
"""

candidato1 = 0
candidato2 = 0
candidato3 = 0
candidato4 = 0
nulo = 0
branco = 0

for i in range(1, 21):
  voto = int(input(f'Digite o voto do funcionário {i}: '))

  while voto < 0 or voto > 6:
    print("Insira um valor entre 0 e 6")
    voto = int(input(f'Digite o voto do funcionário {i}: '))

  if voto == 1:
    candidato1 += 1
  elif voto == 2:
    candidato2 += 1
  elif voto == 3:
    candidato3 += 1
  elif voto == 4:
    candidato4 += 1
  elif voto == 5:
    nulo += 1
  elif voto == 6:
    branco += 1

print('Candidato 1: ', candidato1)
print('Candidato 2: ', candidato2)
print('Candidato 3: ', candidato3)
print('Candidato 4: ', candidato4)
print('Votos nulos: ', nulo)
print('Votos em branco: ', branco)

votos_nulos = (nulo / (candidato1 + candidato2 + candidato3 + candidato4 + nulo + branco)) * 100
votos_brancos = (branco / (candidato1 + candidato2 + candidato3 + candidato4 + nulo + branco)) * 100

print(f'Porcentagem de votos nulos: {votos_nulos}%')
print(f'Porcentagem de votos em branco: {votos_brancos}%')

"""## Aula 5 - Estruturas de dados

### Aquecendo na programação
"""

loja = {'nomes': ['televisão', 'celular', 'notebook', 'geladeira', 'fogão'],
        'precos': [2000, 1500, 3500, 4000, 1500]}

for chave, elementos in loja.items():
  print(f'Chave: {chave}\nElementos:')
  for dado in elementos:
    print(dado)

"""#### Questão 1
Faça um programa que tenha a seguinte lista contendo os valores de gastos de uma empresa de papel `[2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]`. Com esses valores, faça um programa que calcule a média de gastos. Dica, use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).
"""

# Calculadora de média de Gastos
valoresGastos = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]

somaValores = sum(valoresGastos)
quantidadeValores = len(valoresGastos)

calculoMedia = somaValores / quantidadeValores
print(calculoMedia)

"""#### Questão 2
 Com os mesmos dados da questão anterior, defina quantas compras foram acima de 3000 reais e calcule a porcentagem quanto ao total de compras.
"""

quantidade_maior_3000 = 0

# Compras acima de 3000
for i in valoresGastos:
  if i > 3000:
    quantidade_maior_3000 += 1
print(f'foram {quantidade_maior_3000} produtos')
print(f'{(quantidade_maior_3000/quantidadeValores) * 100}% foram acima de 3000 reais')

"""#### Questão 3
Faça um código que colete em uma lista 5 números inteiros quaisquer e imprima a lista. Exemplo: `[1,4,7,2,4]`.
"""

# Definindo a lista
lista = []
# Estrutura de repetição para os 5 numeros
for i in range(1, 6):
  coletaNum = float(input(f'Digite o {i}° número que deseja adicionar: ')) # Coleta os numeros
  adicionaLista = lista.append(coletaNum) # Adiciona dentro da lista

# Imprimindo o resultado
print(lista)

"""#### Questão 4
Colete novamente 5 inteiros e imprima a lista em ordem inversa à enviada.
"""

# Definindo a lista
lista = []
# Estrutura de repetição para os 5 numeros
for i in range(1, 6):
  coletaNum = float(input(f'Digite o {i}° número que deseja adicionar: ')) # Coleta os numeros
  adicionaLista = lista.append(coletaNum) # Adiciona dentro da lista

# Invertendo a ordem
inverte = lista.reverse()

# Imprimindo o resultado
print(lista)

"""#### Questão 5
Faça um programa que, ao inserir um número qualquer, criará uma lista contendo todos os números primos entre 1 e o número digitado.
"""

# Numero que definirá a lista
num = int(input('Digite um número inteiro: '))

# Cria a lista
lista5 = []

# Inicio do loop
for i in range(2, num):

  primo = True

  # Testando se é primo
  for testes in range(2, i):
    if i % testes == 0:
      primo = False
      break

  # Adiciona os valores primos em lista5
  if primo:
    lista5.append(i)

# Imprime os numeros primos
print(lista5)

"""#### Questão 6
Escreva um programa que peça uma data informando o dia, mês e ano e determine se ela é uma data válida para uma análise.
"""

# Coletamos a data
dia = int(input('Digite o dia: '))
mes = int(input('Digite o mês: '))
ano = int(input('Digite o ano: '))

# Análise de fevereiro
if mes == 2:
  # Verificamos se é ou não um ano bissexto
  if ano % 4 == 0 and (ano % 400 == 0 or ano % 100 != 0):
    dias_fevereiro = 29
  else:
    dias_fevereiro = 28
  # Verificamos se o dia colocado corresponde ao máximo de dias de fevereiro
  if dia >= 1 and dia <= dias_fevereiro:
    print('Data válida')
  else:
    print('Data inválida')
# Verificamos meses terminados em 31 dias
elif mes in [1, 3, 5, 7, 8, 10, 12]:
  if dia >= 1 and dia <= 31:
    print('Data válida')
  else:
    print('Data inválida')
# Verificamos meses terminados em 30 dias
elif mes in [4, 6, 9, 11]:
  if dia >= 1 and dia <= 30:
    print('Data válida')
  else:
    print('Data inválida')
# Caso o mês não esteja entre 1 e 12
else:
  print('Data inválida')

"""### Momento dos projetos

#### Questão 7
Para um estudo envolvendo o nível de multiplicação de bactérias em uma colônia, foi coletado o número de bactérias multiplicadas por dia, com base em um processo de duplicação diária e pode ser observado a seguir: `[1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]`. Tendo esses valores, faça um código que gere uma lista contendo o percentual de crescimento de bactérias por dia, comparando o número de bactérias em cada dia com o número de bactérias do dia anterior. Dica: para calcular o percentual de crescimento usamos a seguinte equação: `100 * (amostra_atual - amostra_passada) / (amostra_passada)`.
"""

bacterias = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]

percentual_crescimento = []

for i in range(1, len(bacterias)):
  percentual = 100 * (bacterias[i] - bacterias[i - 1]) / bacterias[i - 1]
  percentual_crescimento.append(percentual)

print(percentual_crescimento)

"""#### Questão 8
Para uma seleção de produtos alimentícios, precisamos separar o conjunto de IDs dados por números inteiros, sabendo que os produtos com ID par são doces e os com ID ímpar são amargos. Monte um código que colete 10 IDs. Depois, calcule e mostre a quantidade de produtos doces e amargos.
"""

IDs_Doces = []
IDs_Amargos = []

for i in range(1, 11):
  ID = int(input(f'Digite o {i}° ID: \nID par: Doces | ID ímpar: Amargos\n'))
  if ID % 2 == 0:
    IDs_Doces.append(ID)
  else:
    IDs_Amargos.append(ID)

print(f'Quantidade de produtos doces: {len(IDs_Doces)}')
print(f'Quantidade de produtos amargos: {len(IDs_Amargos)}')

"""#### Questão 9
Desenvolva um programa que informa a nota de um aluno de acordo com suas respostas. Ele deve pedir a resposta de um aluno para cada questão e é preciso verificar se a resposta foi igual ao gabarito. Cada questão vale um ponto e existem alternativas:  A, B, C ou D.
```
Gabarito da Prova:
01 - D
02 - A
03 - C
04 - B
05 - A
06 - D
07 - C
08 - C
09 - A
10 - B
```
"""

notaAluno = 0
gabarito = {1: 'D', 2: 'A', 3: 'C', 4: 'B', 5: 'A', 6: 'D', 7: 'C', 8: 'C', 9: 'A', 10: 'B'}

for i in range(1, 11):
  resposta = input(f'Digite a resposta da {i}° questão: \n(A | B | C | D)\n')
  if resposta == gabarito[i]:
    notaAluno += 1
    print('Resposta correta')
  else: print('Resposta incorreta')

if notaAluno >= 7:
  print(f'A nota do aluno foi {notaAluno}\nParabéns')
elif notaAluno < 7 and notaAluno >= 5:
  print(f'A nota do aluno foi {notaAluno}\nVocê pode melhorar')
else: print(f'A nota do aluno foi {notaAluno}\nEstude mais')

"""#### Questão 10
Um instituto de meteorologia deseja fazer um estudo de temperatura média de cada mês do ano. Para isso, você precisa fazer um código que colete e armazene essas temperaturas médias em uma lista. Depois, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual, e em que mês elas ocorreram, mostrando os meses por extenso: Janeiro, Fevereiro, etc.
"""

temperaturaMedia = []

mesesAno = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

for i in range(1, 13):
  temperatura = float(input(f'Digite a temperatura média do mês {i}: '))
  temperaturaMedia.append(temperatura)

somaTemperatura = sum(temperaturaMedia)
quantidadeTemperatura = len(temperaturaMedia)

mediaAnual = somaTemperatura / quantidadeTemperatura

for j in range(0, 12):
  if temperaturaMedia[j] > mediaAnual:
    print(f'A temperatura média do mês {mesesAno[j]} foi acima da média anual')

"""#### Questão 11
Uma empresa de e-commerce está interessada em analisar as vendas dos seus produtos. Os dados das vendas foram armazenados em um dicionário:
```
{'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}
```
Escreva um código que calcule o total de vendas e o produto mais vendido.
"""

venda = {'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
        'Produto D': 200, 'Produto E': 250, 'Produto F': 30}

totalVendas = sum(venda.values())
print(f'O total de vendas foi de {totalVendas}')

produtoMaisVendido = ''
maiorQuantidade = 0

for produto in venda:
  if venda[produto] > maiorQuantidade:
    maiorQuantidade = venda[produto]
    produtoMaisVendido = produto

print(f'O produto mais vendido foi o {produtoMaisVendido}')

"""#### Questão 12
Uma pesquisa de mercado foi feita para decidir qual design de uma marca infantil mais agrada crianças. A pesquisa foi feita e o votos computados podem ser observados abaixo:
```
'''
Tabela de votos da marca
Design 1 - 1334 votos
Design 2 - 982 votos
Design 3 - 1751 votos
Design 4 - 210 votos
Design 5 - 1811 votos
'''
```
Adapte os dados fornecidos a você para uma estrutura de dicionário e a partir dele, informe o design vencedor e a porcentagem de votos recebidos.

"""

tabelaVotosMarca = {'Desing1': 1334,'Desing2': 982, 'Desing3': 1751,
                    'Desing4': 210, 'Desing5': 1811}

totalVotos = sum(tabelaVotosMarca.values())

marcaMaisVotada = ''
maiorQuantidade = 0

for desing in tabelaVotosMarca:
  if tabelaVotosMarca[desing] > maiorQuantidade:
    maiorQuantidade = tabelaVotosMarca[desing]
    marcaMaisVotada = desing

print(f'O produto mais vendido foi o {produtoMaisVendido} com {(maiorQuantidade/totalVotos)*100: .2f}%')

"""#### Questão 13
Os funcionários de um setor da empresa que você trabalha vão receber um abono correspondente a 10% do seu salário devido ao ótimo desempenho do time. O setor financeiro solicitou sua ajuda para a verificação das consequências financeiras que esse abono irá gerar nos recursos. Assim, foi encaminhada para você uma lista com os salários que receberão o abono: `[1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]`. O abono de cada funcionário não pode ser inferior a 200. Em código, transforme cada um dos salários em chaves de um dicionário e o abono de cada salário no elemento. Depois, informe o total de gastos com o abono, quantos funcionários receberam o abono mínimo e qual o maior valor de abono fornecido.

"""

# Lista de salários
salarios = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]
# Inicializamos as variáveis
dic_abonos = {} # Dicionário de abonos
total_abono = 0 # Irá somar todos os gastos com abono
abonos_minimo = 0 # Irá armazenar a quantidade de abonos mínimos
maior_abono = 0 # Irá armazenar o maior valor de abono

# Percorremos toda a lista de salários
for salario in salarios:
  # Calculamos o valor teórico de abono
  abono = salario * 0.1
  # Caso o abono seja inferior a 200,
  # ajustamos o valor de abono para o mínimo (200)
  if abono < 200:
    abono = 200
  # Adicionamos um novo dado no dicionário chave abono
  dic_abonos[salario] = abono

# Percorremos todos os valores do dicionário de abonos
for abono in dic_abonos.values():
  # Contamos o salário minimo
  if abono == 200:
    abonos_minimo += 1
  # Verificamos se o abono lido é maior que o valor armazenado em maior_abono
  # Cada vez que o abono superar o valor de maior_abono,
  # a variável maior_abono vai ser igual à abono, atribuindo um novo valor
  if abono > maior_abono:
    maior_abono = abono
  # Somamos os abonos
  total_abono += abono
# Resultados
print(f'Abonos: {dic_abonos}')
print(f'Total de gasto com abonos: {total_abono}')
print(f'Número de funcionários que receberam o abono mínimo: {abonos_minimo}')
print(f'Maior valor de abono: {maior_abono: .2f}')

"""#### Questão 14
Uma equipe de cientistas de dados está estudando a diversidade biológica em uma floresta. A equipe fez a coleta de informações sobre o número de espécies de plantas e animais em cada área da floresta e armazenaram essas informações em um dicionário. Nele, a chave descreve a área dos dados e os valores nas listas correspondem às espécies de plantas e animais nas áreas, respectivamente.
```
{'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}
```
Escreva um código para calcular a média de espécies por área e identificar a área com a maior diversidade biológica. Dica: use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).

"""

# Especificamos os dados para um dicionário
dados = {'Área Norte': [2819, 7236],
         'Área Leste': [1440, 9492],
         'Área Sul': [5969, 7496],
         'Área Oeste': [14446, 49688],
         'Área Centro': [22558, 45148]}
# Inicializamos as variáveis
soma_media = 0 # Irá somar todas as médias
maior_diversidade = '' # Irá armazenar a área com maior diversidade
maior_soma = 0 # Irá armazenar a maior soma de espécies
# Percorremos os valores de chaves e elementos do dicionário
for area, especies in dados.items():
  # Fazemos a soma do números de espécies em cada área com a função sum
  soma_especies = sum(especies)
  # Calculamos a média dividindo a soma das espécies pela quantidade de espécies
  media = soma_especies / len(especies)
  # Imprimimos
  print(f'A {area} tem a média de {media} espécies')
  # Verificamos se a soma das espécies é maior que o valor armazenado de maior_soma
  # Cada vez que a soma_especies superar o valor de maior_soma,
  # a variável maior_soma vai ser igual à soma_especies, atribuindo um novo valor
  # De forma similar, maior_diversidade também é substituída
  if soma_especies > maior_soma:
      maior_soma = soma_especies
      maior_diversidade = area
  # Somamos as médias
  soma_media += media
# A média total será dada pela soma_media dividida pela quantidade de áreas
media_total = soma_media / len(dados)
print(f'Média geral de espécies: {media_total}')
print(f'Área com a maior diversidade biológica: {maior_diversidade}')

"""#### Questão 15
O setor de RH da sua empresa te pediu uma ajuda para analisar as idades dos funcionários de 4 setores da empresa. Para isso, ele te forneceu os seguintes dados:
```
{'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
```
Sabendo que cada setor tem 10 funcionários, construa um código que calcule a média de idade de cada setor, a idade média geral entre todos os setores e quantas pessoas estão acima da idade média geral.

"""

# Especificamos os dados para um dicionário
dados = {'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
        'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
        'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
        'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
# Inicializamos a variável que irá somar todas as idades
total_idades = 0
# Percorremos os valores de chaves e elementos do dicionário
for setor, idades in dados.items():
  # Calculamos a média dividindo a soma das idades pela quantidade funcionários em cada setor
  media_idade = sum(idades) / len(idades)
  # Imprimimos
  print(f'O {setor} tem a média de {media_idade}')
  # Somamos as médias
  total_idades += sum(idades)
# A média total será dada pela total_idades dividida pela quantidade de pessoas totais (setores * funcionários por setor)
media_total = total_idades / (len(idades) * len(dados))
print(f'A média de idade geral é {media_total}')

# Inicializamos a variável que irá contar todas pessoas com idade acima da média
acima_media = 0
# Percorremos novamente os valores de chaves e elementos do dicionário
for setor, idades in dados.items():
  # Lemos os elementos (idades) dentro de cada lista de idades no dicionário
  for id in idades:
    # Verificamos se o valor da idade é superior à média total
    if id > media_total:
      # Caso o valor da idade seja superior à média, incrementamos mais um no contador
      acima_media += 1
# Resultado
print(f'{acima_media} pessoas estão acima da idade média geral')